//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace SpaceDebris.Web.Models.ModelsBuilder
{
	// Mixin Content Type with alias "teamMemberComp"
	/// <summary>Team Member Comp</summary>
	public partial interface ITeamMemberComp : IPublishedElement
	{
		/// <summary>Team member description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		string TeamMemberDescription { get; }

		/// <summary>Team member image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		global::Umbraco.Core.Models.MediaWithCrops TeamMemberImage { get; }

		/// <summary>Team member name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		string TeamMemberName { get; }

		/// <summary>Team member title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		string TeamMemberTitle { get; }
	}

	/// <summary>Team Member Comp</summary>
	[PublishedModel("teamMemberComp")]
	public partial class TeamMemberComp : PublishedElementModel, ITeamMemberComp
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const string ModelTypeAlias = "teamMemberComp";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TeamMemberComp, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public TeamMemberComp(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Team member description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("teamMemberDescription")]
		public virtual string TeamMemberDescription => GetTeamMemberDescription(this);

		/// <summary>Static getter for Team member description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static string GetTeamMemberDescription(ITeamMemberComp that) => that.Value<string>("teamMemberDescription");

		///<summary>
		/// Team member image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("teamMemberImage")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops TeamMemberImage => GetTeamMemberImage(this);

		/// <summary>Static getter for Team member image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static global::Umbraco.Core.Models.MediaWithCrops GetTeamMemberImage(ITeamMemberComp that) => that.Value<global::Umbraco.Core.Models.MediaWithCrops>("teamMemberImage");

		///<summary>
		/// Team member name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("teamMemberName")]
		public virtual string TeamMemberName => GetTeamMemberName(this);

		/// <summary>Static getter for Team member name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static string GetTeamMemberName(ITeamMemberComp that) => that.Value<string>("teamMemberName");

		///<summary>
		/// Team member title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("teamMemberTitle")]
		public virtual string TeamMemberTitle => GetTeamMemberTitle(this);

		/// <summary>Static getter for Team member title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static string GetTeamMemberTitle(ITeamMemberComp that) => that.Value<string>("teamMemberTitle");
	}
}
